### PR TITLE
issue #49, update README

### PR DESCRIPTION
**Pull request by LegionAtol**
HI! I'm new to QuTiP and would like to contribute

Added instruction in README.md for formatting `.md` files with `nbQA`

### CODE REVIEW

**Comment by christian512** [comment]
Hi @LegionAtol,
thanks for the contribution :) 
I left a short comment. When you adapt the changes we can merge your changes to the `Readme.md`!

**Comment by LegionAtol** [comment]
Hi, is there something wrong?

**Comment by ajgpitch** [comment]
> Hi @LegionAtol, thanks for the contribution :) I left a short comment. 
@christian512 It's not clear to me either where you left this comment

**Comment by hodgestar** [comment]
Looks good. Merging.

**Comment by hodgestar** [comment]
Thanks @LegionAtol!

**Pull request merged**
