### PR TITLE
Adding Tutorials for Circuit Renderers

### PR DESCRIPTION
**Pull request by gadhvirushiraj**
# New Renderer Tutorials
### GSOC'24 Project - QuTiP: Enhanced Quantum Circuit Diagrams

✅ **TextRenderer Tutorial** 
✅ **MatRenderer Tutorial**

### CODE REVIEW

**Comment by BoxiLi** [comment]
@gadhvirushiraj Could you maybe push something, e.g. add a `qutip.about()` as the last cell just to try triggering the tests again?

**Comment by gadhvirushiraj** [comment]
Is `qc.add_1q_gate()` still supported to add gates across all present qubits in circuit? It used to work earlier, though showing some warning now. I have removed it from current tutorial examples.

**Comment by BoxiLi** [comment]
It should be supported, but I did remember making some changes on that a few weeks ago. Maybe something went wrong. What was the error?

**Comment by nwlambert** [comment]
@gadhvirushiraj if you update your branch the tests should now run.   some of the plotting stuff in old qip plotting examples now fail and need updating to the new draw() method. I tried in the other PR but these produced additional issues, so maybe better you check here (one had trouble parsing a latex label, and the other failed completely).

**Comment by gadhvirushiraj** [comment]
This should work after https://github.com/qutip/qutip-qip/pull/257 merge.

**Comment by nwlambert** [comment]
these look good now.  thanks rushi.  for the v4 failing test, maybe we need to fix the numpy test environment to 1.20 or lower?

**Comment by nwlambert** [comment]
Sorry rushi, that seemed to make things worse.  can you revert that change to the numpy version, and I will see if I can produce the original problem locally.

**Comment by gadhvirushiraj** [comment]
> Sorry rushi, that seemed to make things worse. can you revert that change to the numpy version, and I will see if I can produce the original problem locally.

I have reverted the changes, but I previously verified that `np.complex` (used internally) has been deprecated starting with version `1.20`, as you mentioned. I believe we also need to use `python 3.9` to ensure compatibility with numpy.

**Comment by nwlambert** [comment]
I think we can just fix it by using the right dtype in the notebook, `mat = np.zeros((4, 4), dtype=complex)`

**Comment by nwlambert** [comment]
latest jax release (0.4.36) breaks something in qutip-jax, but v4 tests are finally running, so will merge

**Pull request merged**
