### PR TITLE
sort args of sphereplot

### PR DESCRIPTION
**Pull request by tamakoshi2001**
Change the order of args of sphereplot
Related [#2219](https://github.com/qutip/qutip/pull/2219)

### CODE REVIEW

**Comment by tamakoshi2001** [comment]
@Ericgig This PR is for [#2219](https://github.com/qutip/qutip/pull/2219). I just changed the order of arguments.

**Comment by tamakoshi2001** [comment]
@nwlambert Could you review the change and run the build again?

**Comment by Ericgig** [comment]
This is included in the previous PR #67. Can we close?

**Comment by tamakoshi2001** [comment]
@Ericgig Yes we can.

**Pull request closed without merging**
