### PR TITLE
Port single-photon-interference tutorial

### PR DESCRIPTION
**Pull request by rochisha0**
### What does this PR do?

This PR ports a new tutorial on single photon interference for both v4 and v5

### Related Issues:

- Follows #18

### CODE REVIEW

**Comment by Ericgig** [comment]
Thank you for your interest in contributing to qutip.

Where does this example comes from?
From a quick look, it does not seems use qutip feature that much...

**Comment by rochisha0** [comment]
@Ericgig Thank you for the comment. It is one of the notebooks suggested to port (4th one) by @hodgestar in the issue #18

**Comment by hodgestar** [comment]
@Ericgig: This notebook was the result of an undergraduate student project that I supervised.

**Comment by rochisha0** [comment]
@hodgestar Thank you for the feedback. I have made the changes to the formatting style of the notebook. I hope it works. I will make the changes to the website template once we figure out a good folder name.

**Comment by rochisha0** [comment]
@hodgestar How does physics tutorials sound for the folder name?

**Comment by hodgestar** [comment]
@rochisha0 On second thoughts, let's stick with `miscellaneous`. At least it will give us somewhere to put this and other once-off tutorials until we see a pattern emerging.

**Comment by hodgestar** [comment]
It looks like there is still one linting error:
```
notebooks/miscellaneous/single-photon-interference.ipynb:cell_2:1:1: F821 undefined name 'Image'
```

**Comment by rochisha0** [comment]
@hodgestar Looks like there were some manual changes to be made regarding `comments` and `images` in the notebooks that were not supported by `black` and `isort`. I have made the necessary changes to the template, but I cannot find any build information to cross-check that.

**Comment by christian512** [comment]
I can not trigger a workflow (guess I'm missing some permission). But I have checked your notebooks using `flake8 --max-line-length=88` (as in our linting checks) and it all seems good! 

@hodgestar  I think this is ready for merging! :)

**Comment by hodgestar** [comment]
Thanks @christian512. I don't know why the CI didn't run, but let me merge this and see what happens.

**Comment by hodgestar** [comment]
@rochisha0 The ported tutorial is now published at http://qutip.org/qutip-tutorials/ -- thank you!

I noticed that there are few minor things that need fixing on the published page that are related to this PR:

- The new "Miscellaneous" section is missing from the index at the top (the one immediately after "The following are the contents of this page:")
- The title of the notebook in the "Miscellaneous" section list is "HV Basis". I'm guessing this is because the logic for picking up the title is subtly wrong.

Would you be up  to making a new PR to address these?

**Comment by rochisha0** [comment]
@hodgestar Yes, I'll take this up.

**Comment by hodgestar** [comment]
Thanks, @rochisha0!

**Pull request merged**
